### ISSUE TITLE
Pasting text doesn't work

### ISSUE THREAD

**Issue by wendellestradairely** [kaaaaaaaaaaai/paragraph-with-alignment#1]
I tried to plug this tool in because EditorJS doesn't have text alignment by default but when pasting a text content, it doesn't paste anything except whitespaces.

**Comment by kaaaaaaaaaaai** [comment]
@wendellestradairely 
ok!
 i try and fixing, thanks for the report.

**Comment by kaaaaaaaaaaai** [comment]
https://github.com/kaaaaaaaaaaai/paragraph-with-alignment/releases/tag/v1.1.0
