### ISSUE TITLE
Console.log in distributed bundle

### ISSUE THREAD

**Issue by Gbuomprisco** [kaaaaaaaaaaai/paragraph-with-alignment#6]
Hi,

There is a console.log in the bundle distributed to NPM (although I cannot see it in the source code). Would it be possible to publish a new version?

Thanks!

**Comment by mqtik** [comment]
I sent a pull request.
It's only on the bundle.

**Comment by Gbuomprisco** [comment]
No reply, I'll probably rewrite this

**Comment by kaaaaaaaaaaai** [comment]
sry, its released, new issue if still problems
